version: '3'
services:
  app:
    build: .
    command: 'go run main.go'
    volumes:
      - .:/go/src/github.com/twelvelabs/wordcount:cached
    ports:
      - 80:80
    stdin_open: true
    tty: true
