version: '3'
services:
  app:
    build: .
    command: bin/server
    volumes:
      - .:/go/src/github.com/twelvelabs/wordcount:cached
      - ./home:/home/wordcount
    ports:
      - 80:80
    stdin_open: true
    tty: true
  ansible:
    image: williamyeh/ansible:alpine3
    environment:
      ANSIBLE_CONFIG: /ansible/ansible.cfg
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ./ansible:/ansible
      - ./home:/home/wordcount
